name: ci
run-name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Fetch Node Version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: yarn

      - name: Run Linter
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: blog_service
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
    env:
      DATABASE_URL: 'postgres://user:password@localhost/blog_service'
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Fetch Node Version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: yarn

      - name: Migrate Database
        run: yarn db:migrate

      - name: Run Tests
        run: yarn test
